name: todo_app
description: Simple To Do app.

publish_to: 'none'

version: 1.2.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  path_provider: ^1.6.14
  sqflite: ^1.3.1+1
  provider: ^4.3.2+1
  shared_preferences: ^0.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
